version: '3'
services:
  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - "8080:80" # ローカルの8080ポートをコンテナの80ポートにマッピング
    volumes:
      - ./html:/usr/local/apache2/htdocs/
      - ./css:/usr/local/apache2/htdocs/css
